### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [tvlad1234/pico-rv32ima#11]
Hi there,
I have the following questions:

1. How to disable display and keyboard? (To save memory)
2. What are the UART pins?
3. Are there any PSRAM chip alternatives that are in DIP package?
4. Can we replace PSRAM chips with IIC EEPROMs? (They might be a little slower, but is it possible and if yes, how and what are the basic requirements?)

**Comment by tvlad1234** [comment]
Hi! To disable the display and keyboard, look in the [rv32_config.h](https://github.com/tvlad1234/pico-rv32ima/blob/main/pico-rv32ima/rv32_config.h) file, line 27 and set the `CONSOLE_LCD` define to 0. The UART is not enabled by default, only the USB console. To enable the UART, at line 21, set the `CONSOLE_UART` define to 1. The default UART pins are 0 and 1 (see lines 42 and 43), at 115200 baud.

There aren't any PSRAM chips in DIP package as far as I'm aware, but you could use the ones I mentioned and solder them to an adapter. 

Regarding the IIC EEPROMs, they are definitely a lot slower. Before I got the PSRAM, I was using an SD card to simulate the RAM and it was unusable with Linux (it would take 15 minutes to boot and then it locked up). An SD card is hundreds of times faster than an IIC EEPROM. You can try it if you wish to do so but it probably won't work that well. To do it, you need to rewrite the `accessPSRAM` function in psram.c with your EEPROM access routines.

**Comment by ElectroBoy404NotFound** [comment]
Hi @tvlad1234 !
Thank you for your fast answer!
1: I managed to delete all the lines and libs needed for Display and PS2 and CDC without breaking anything (A new record for me!).
2: I actually dont have access to any pcb manufacturing companies. So i need them in the dip package.
3: What about 25C64 SPI EEPROMs? Would they work or will it lock up like the problem you mentioned?

**Comment by tvlad1234** [comment]
I don't think there are any PSRAM chips made in DIP package, they're a recent invention and the pinout is meant to be compatible with SPI flash chips, those never existed in DIP package. Try looking at online part suppliers for this kind of adapter 
![image](https://github.com/tvlad1234/pico-rv32ima/assets/60291077/e76e6d3e-4c8c-42dd-8cc5-3d856dc950da).

I don't think SPI EEPROMs would work properly either. The read and write access times are just too slow. Also, it's very likely you'll wear out the memory cells in no time.

**Comment by ElectroBoy404NotFound** [comment]
Ah, i see. I'm going to close this issue. Thank you for answering my questions! I will come back if i find any of them in DIP.

**Comment by ElectroBoy404NotFound** [comment]
Will SRAM chips work?

**Comment by tvlad1234** [comment]
If you can find them in large enough capacity, they probably will. Keep in mind you need at least 16 megabytes to run Linux.

**Comment by ElectroBoy404NotFound** [comment]
Ok..

**Comment by ElectroBoy404NotFound** [comment]
Can i use SIMM 30 pin RAM?

**Comment by ElectroBoy404NotFound** [comment]
Or is it possible to use ANY SRAM?

**Comment by tvlad1234** [comment]
If you have a way of interfacing it to the pico, any RAM of sufficient capacity should work.

**Comment by ElectroBoy404NotFound** [comment]
I see..

**Comment by ElectroBoy404NotFound** [comment]
What is the best alternative i can use that is in DIP package? Can i use an STM32 to simulate a PSRAM chip?

**Comment by ElectroBoy404NotFound** [comment]
I see. I will try to find some.
