### ISSUE TITLE
Write error at address 3072

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [tvlad1234/pico-rv32ima#13]
Hi there,
I tried to use this program, an old commit of the program that used SD-RAM instead of PS-RAM.
But it is giving this error. How to fix it? I dont have any PS-RAM available in my area.

**Comment by tvlad1234** [comment]
Also, make sure your card is formatted as FAT or exFAT, with a block size from 1024 to 2048.

**Comment by ElectroBoy404NotFound** [comment]
> Also, make sure your card is formatted as FAT or exFAT, with a block size from 1024 to 2048 bytes.

Hi,
My SD card only supportes block size of 4k and i cant format it as FAT; only as FAT32

**Comment by tvlad1234** [comment]
Yes, FAT32, sorry. Try formatting as exFAT.

**Comment by tvlad1234** [comment]
As mentioned, keep wiring as short as possible, and avoid breadboards.

**Comment by tvlad1234** [comment]
Open the format dialog, and select the format to be exFAT

**Comment by ElectroBoy404NotFound** [comment]
![image](https://github.com/tvlad1234/pico-rv32ima/assets/89782177/cb598f1f-afad-47d6-a743-307d8062ddb2)

**Comment by ElectroBoy404NotFound** [comment]
> I am sorry, that is definitely not my program running.

It uses the same program.

**Comment by tvlad1234** [comment]
It might use the same emulator core, but it is not the project contained in this repo. I cannot help with troubleshooting further, as I don't know the specifics of that implementation

**Comment by ElectroBoy404NotFound** [comment]
I mean, it uses the same SD-RAM implementation (copy-paste of it)

**Comment by tvlad1234** [comment]
I don't know how it operates beyond the RAM implementation. There may be a multitude of reasons for it failing, especially if it does at the same address.

**Comment by tvlad1234** [comment]
As mentioned many times already, the only way to make this project work properly is to use PSRAM (or some other form of *real* RAM, with a compatible interface), this was the primary reason why I scrapped the SD card emulation thing.

**Comment by tvlad1234** [comment]
Try using one of my earlier commits (as-is, without any modifications).
