### ISSUE TITLE
Memory speed Improvement?

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [tvlad1234/pico-rv32ima#14]
Hi there,

What if we move the ram write to another core? Then the writes can be buffered on the other core till they can be written. Will that speed up things? Does it even work?

**Comment by tvlad1234** [comment]
Hi!

We already something like this in the cache implementation, moving it to the other core would actually introduce some latency due to the overhead of working with the inter-core FIFO.

**Comment by ElectroBoy404NotFound** [comment]
Ah OK.
