### ISSUE TITLE
About Linux?

### ISSUE THREAD

**Issue by killeradhil** [tvlad1234/pico-rv32ima#16]
I need to know about the Linux? Iam beginner so I don't know about the kernel development 😔. 
  To get answers like 
- is it Embedded Linux or not?
-source code?
- packages exist default ?

Can you suggest way to learn kernel image build ?

**Comment by ElectroBoy404NotFound** [comment]
> is it Embedded Linux or not?
Yes!

> -source code?
It uses the main-line kernel with a few patches.

> packages exist default ?
WDYM packages?

**Comment by killeradhil** [comment]
> WDYM packages?

Like gcc,  nano etc
